---
title: "Final Project 2 Covid19 Data"
author: "William Vernon"
date: "2024-02-29"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2)
```

```{r }
url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

file_names <- c("time_series_covid19_confirmed_global.csv","time_series_covid19_deaths_global.csv","time_series_covid19_confirmed_US.csv", "time_series_covid19_deaths_US.csv")

urls <- str_c(url_in,file_names)

```

```{r import_data, message = FALSE}
global_cases <- read_csv(urls[1])
global_deaths <- read_csv(urls[2])
US_cases <- read_csv(urls[3])
US_deaths <- read_csv(urls[4])

```

```{r global_data}

# Reshape global_cases from wide to long format, removing Lat and Long columns
global_cases_long <- global_cases %>%
  pivot_longer(
    cols = -c("Province/State", "Country/Region", Lat, Long),
    names_to = "date", 
    values_to = "cases"
  ) %>%
  select(-c(Lat, Long))

# Reshape global_deaths from wide to long format, removing Lat and Long columns
global_deaths_long <- global_deaths %>%
  pivot_longer(
    cols = -c("Province/State", "Country/Region", Lat, Long),
    names_to = "date", 
    values_to = "deaths"
  ) %>%
  select(-c(Lat, Long))

# Join the cases and deaths data frames, rename columns, and convert date format
global <- global_cases_long %>%
  full_join(global_deaths_long, by = c("Province/State", "Country/Region", "date")) %>%
  rename(
    Country_Region = "Country/Region",
    Province_State = "Province/State"
  ) %>%
  mutate(date = mdy(date))

```

```{r summary}
summary(global)
```

```{r }
# Remove any cases that are 0
global <- global %>% filter(cases > 0)

summary(global)

```

## US Cases
```{r US Cases}
# Cleaning US_cases
US_cases <- US_cases %>%
    pivot_longer(cols = -(UID:Combined_Key),
                 names_to = "date",
                 values_to = "cases") %>%
    select(Admin2:cases) %>%
    mutate(date = mdy(date)) %>%
    select(-c(Lat, Long_))

US_deaths <- US_deaths %>%
    pivot_longer(cols = -(UID:Population),
                 names_to = "date",
                 values_to = "deaths") %>%
    select(Admin2:deaths) %>%
    mutate(date = mdy(date)) %>%
    select(-c(Lat, Long_))

# Joining US_cases and US_deaths
US <- US_cases %>%
    full_join(US_deaths)

# Combined Keys so both data sets have the same keys
global <- global %>%
    unite("Combined_Key",
          c(Province_State, Country_Region),
          sep = ", ",
          na.rm = TRUE,
          remove = FALSE)
global

```

```{r}
uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"
uid <- read_csv(uid_lookup_url, show_col_types = FALSE) %>%
  select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))
```

```{r}
global <- global %>%
    left_join(uid, by = c("Province_State", "Country_Region")) %>%
    select(-c(UID, FIPS)) %>%
    select(Province_State, Country_Region, date,
           cases, deaths, Population,
           Combined_Key)
global
```


## Visualizing Data
```{r visualize data}
# Visualizing the Data

US_by_state <- US %>%
    group_by(Province_State, Country_Region, date) %>%
    summarize(cases = sum(cases), deaths = sum(deaths),
              Population = sum(Population)) %>%
    mutate(deaths_per_mill = deaths *1000000 / Population) %>%
    select(Province_State, Country_Region, date,
           cases, deaths, deaths_per_mill, Population) %>%
    ungroup()


tail(US_by_state)

US_totals <- US_by_state %>%
    group_by(Country_Region, date) %>%
    summarize(cases = sum(cases), deaths = sum(deaths),
              Population = sum(Population), .groups = "drop") %>%
    mutate(deaths_per_mill = deaths * 1000000 / Population) %>%
    select(Country_Region, date, cases, deaths, deaths_per_mill, Population) %>%
    ungroup()

tail(US_totals)

US_totals %>%
    filter(cases > 0) %>%
    ggplot(aes(x = date, y = cases)) +
    geom_line(aes(color = "cases")) +
    geom_point(aes(color = "cases" )) +
    geom_line(aes(y = deaths, color = "deaths")) +
    geom_point(aes(y = deaths, color = "deaths")) +
    scale_y_log10() +
    theme(legend.position="bottom",
          axis.text.x = element_text(angle = 90)) +
    labs(title = "COVID19 in US", y = NULL)
```

```{r state of New York}
state <- "New York"
US_by_state %>%
    filter(Province_State == state) %>%
    filter(cases > 0, deaths > 0) %>%
    ggplot(aes(x = date, y = cases)) +
    geom_line(aes(color = "cases")) +
    geom_point(aes(color = "cases")) +
    geom_line(aes(y = deaths, color = "deaths")) +
    geom_point(aes(y = deaths, color = "deaths")) +
    scale_y_log10() +
    theme(legend.position="bottom",
          axis.text.x = element_text(angle = 90)) +
    labs(title = paste("COVID19 in", state), y = NULL)

```

```{r}
US_state_totals <- US_by_state %>%
    group_by(Province_State) %>%
    summarise(deaths = max(deaths), cases = max(cases),
              population = max(Population),
              cases_per_thou = 1000 * cases / population,
              deaths_per_thou = 1000 * deaths / population) %>%
    filter(cases > 0, population > 0)

US_state_totals %>%
    slice_min(deaths_per_thou, n = 10)

US_state_totals %>%
    slice_max(deaths_per_thou, n = 10)

```

```{r Model}

# Fit a linear regression model
mod <- lm(deaths_per_thou ~ cases_per_thou, data = US_state_totals)

x_grid <- seq(1, 151)
new_df <- tibble(cases_per_thou = x_grid)
US_state_totals %>% mutate(pred = predict(mod))

US_tot_w_pred <- US_state_totals %>% 
  mutate(pred = predict(mod))

US_tot_w_pred %>% 
  ggplot() +
  geom_point(aes(x = cases_per_thou, y = deaths_per_thou), color = "blue") +
  geom_point(aes(x = cases_per_thou, y = pred), color = "red") +
  labs(title = "Predicted Deaths per Thousand vs. Actual Deaths per Thousand", x = "Cases", y = "Deaths per Thousand")

```